# Copyright (C) 2021-2022 Mo Zhou <cdluminate@gmail.com>
# License: Apache-2.0

reb:
	pdflatex RebuttalTemplate.tex
	bibtex RebuttalTemplate
	pdflatex RebuttalTemplate.tex
	pdflatex RebuttalTemplate.tex
	-evince RebuttalTemplate.pdf
